name: towe_defense
description: Tower Defense game built with Flutter and Flame.
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flame: ^1.18.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/sprites/
